sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - gcov-5
    - libboost1.55-all-dev

install: 
  - sudo apt-get install -qq g++-5
  # - sudo apt-get install -qq gcov-5

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - ./install_githubs.sh
  - ./build_console.sh
  - ./build_desktop.sh
  - ./get_code_cov.sh
  - codecov
